### ISSUE TITLE
Can't find an accellerator device!

### ISSUE THREAD

**Issue by jonathan-chin** [tegan-lamoureux/Rotate-Spectre#1]
First of all, THANK YOU FOR THIS!

I tried running the script but got:

```Can't find an accellerator device!```

How can I fix this? Also, I have a sliightly newer version of the spectre, which has both:

```ELAN0732:00 04F3:24DB
ELAN0732:00 04F3:24DB Pen```

Do I need to modify the script to include both?

**Comment by tegan-lamoureux** [comment]
Oh hey! Of course. :)  

So for the first question - Yeah, it looks like the script might not be finding your accel device. Can you run an `ls` in your `/sys/bus/iio/devices/` directory? That's the industrial i/o subsystem, where all your sensors should be. You should see directories like `iio:device0`, `iio:device1`, etc.  

One of those is going to map to your accelerometer, and will contain files specifically named `in_accel_x_raw` and `in_accel_y_raw`. That full path (`example: /sys/bus/iio/deviced/iio:device0/in_accel_x_raw`) is what the the file objects `accel_x` and `accel_y` on lines 68 and 69 of the script need. 

So, for a quick fix you can just find those paths, and set the following lines:
`68:     accel_x = open(<file path to in_accel_x_raw here>)`
`69:     accel_y = open(<file path to in_accel_y_raw here>)`
while commenting out lines 24-29 where it checks to see what the name is.

As for your second question, yeah, you're going to have to change line 55 to:
`55:    check_call(['xinput', 'set-prop', 'ELAN0732:00 04F3:24DB', 'Coordinate Transformation Matrix',] + s['coord'].split())`

I don't know if you need the `Pen` part, so if it doesn't seem to be working, add that in.

**Comment by tegan-lamoureux** [comment]
If you can let me know the output of your `/sys/bus/iio/devices/` directory, and the contents of the one that contains your accelerometer device, I can try to make the script auto-detect those.

**Comment by jonathan-chin** [comment]
my ```/sys/bus/iio/devices``` directory is empty!

**Comment by tegan-lamoureux** [comment]
Oh no! I wonder if the kernel isn't detecting your accelerometer. Or it's in a different place altogether. I'm running arch linux, I don't know if you have a different distribution or not, maybe it places it somewhere else.

Can you run `udevadm info --export-db`, see if it shows any device paths that may be relevant?

**Comment by tegan-lamoureux** [comment]
You'll also probably have to grep for accel or iio, sorry. I'm not near a linux machine. Try `udevadm info --export-db | grep -e accel -e iio`.

**Comment by jonathan-chin** [comment]
I'm running Xubuntu.

there's nothing in my output from udevadm grepping for accel / iio

what do you suggest?

**Comment by tegan-lamoureux** [comment]
Yeah, my guess is that it's either not detecting your accelerometer (because of a lack of kernel support and/or HP using a different one in your laptop version), or the xubuntu kernel is putting the device file somewhere else. (maybe in /dev/ ?)

I'd check that you're updated to the latest kernel. Then, you could try an Arch linux live cd to see if it's a distribution thing. If it's detected in Arch (in /sys/bus/iio) you may just need to load a module or install a driver on your xubuntu install. I don't know how different the kernels are.

If it visible on your system somewhere, you just need the file path for those open statements, and the script should work.

**Comment by jonathan-chin** [comment]
no problem! thanks!

**Comment by jonathan-chin** [comment]
I figured it out. I had to update my kernel. Works like a charm now.

**Comment by tegan-lamoureux** [comment]
Yay! Glad to hear.
