### ISSUE TITLE
black screen when returning to normal mode

### ISSUE THREAD

**Issue by fubsan** [tegan-lamoureux/Rotate-Spectre#2]
Hi, have you seen the follow issue:

1. launch script
2. turn display upside down
3. Return display to original position (laptop mode)

Actual:
On step 2, rotation works
On step 3, display turns black

Running on Mint 18.3
Devices:
⎜   ↳ ELAN22CA:00 04F3:22CA                   	id=11	[slave  pointer  (2)]
⎜   ↳ ELAN22CA:00 04F3:22CA Pen               	id=12	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=15	[slave  pointer  (2)

4.13.0-19-generic #22~16.04.1-Ubuntu SMP

**Comment by tegan-lamoureux** [comment]
I haven't, sorry. I can check later today when I'm at my laptop though. 

Are you using one of the stable builds of 18.3 (Cinnamon or MATE DE)? It looks like XFCE and KDE are still in Beta, and that may be part of the issue. For what it's worth I'm running mine on the latest Arch linux kernel, with Awesome window manager v4.2.

I'd recommend manually rotating your screen in that sequence of orientations with `xrandr` and see if that reproduces the issue, as that's all the script is doing. If that reproduces it, it's most likely an issue with the way Mint or your display driver is handling things.

**Comment by fubsan** [comment]
Hi,

Using the cinnamon version.
xrandr --output eDP1 --rotate inverted #works
xrandr --output eDP1 --rotate normal #also works

Other than that: Python 2.7.12 maybe?

**Comment by fubsan** [comment]
Yep, it turns out, either Cinnamon or something else has problems with rotating left and right. Same from the actual display settings and not an issue with your script, hence i'll close the issue.
