### ISSUE TITLE
Supporting the pen

### ISSUE THREAD

**Issue by JanusDC** [tegan-lamoureux/Rotate-Spectre#3]
Hi, thank you for the script, I have been using it for a while already. My HP Spectre x360 has also a Pen, here is the output of xinput:

`$ xinput --list`
`⎡ Virtual core pointer                    	id=2	[master pointer  (3)]`
`⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]`
`⎜   ↳ ELAN0732:00 04F3:22E1                   	id=11	[slave  pointer  (2)]`
`⎜   ↳ ELAN0732:00 04F3:22E1 Pen Pen (0)       	id=17	[slave  pointer  (2)]`
`⎜   ↳ SynPS/2 Synaptics TouchPad              	id=14	[slave  pointer  (2)]`
`⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]`
`    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]`
`    ↳ Power Button                            	id=6	[slave  keyboard (3)]`
`    ↳ Video Bus                               	id=7	[slave  keyboard (3)]`
`    ↳ Power Button                            	id=8	[slave  keyboard (3)]`
`    ↳ HP TrueVision FHD RGB-IR: HP Tr         	id=9	[slave  keyboard (3)]`
`    ↳ ELAN0732:00 04F3:22E1 Pen               	id=10	[slave  keyboard (3)]`
`    ↳ Intel Virtual Button driver             	id=12	[slave  keyboard (3)]`
`    ↳ AT Translated Set 2 keyboard            	id=13	[slave  keyboard (3)]`
`    ↳ HP WMI hotkeys                          	id=15	[slave  keyboard (3)]`
`    ↳ HP Wireless hotkeys                     	id=16	[slave  keyboard (3)]`

So, I duplicated the line 55, but changing `ELAN0732:00 04F3:22E1` by `ELAN0732:00 04F3:22E1 Pen Pen (0)`, in the second line. And it seems to work (I just did it, tried it, and it did work). I do not know if (and how) I should check whether the pen is available before running that line, that is why I do not propose the change directly.

Best,
Alejandro

**Comment by tegan-lamoureux** [comment]
Thanks for the information! I've been wanting to make a few changes, so I added that in when I updated it. I scan the output of `xinput --list` and if the string 'Pen (0)' is found, it makes the call you describe. 

I don't have a pen-enabled spectre, but if you have the time, I would love it if you could give the new version a shot! I'm hoping I didn't mess anything up. Note that you can change device names at the top of the file now.

Thanks again.
