### ISSUE TITLE
Error while rotate touchscreen

### ISSUE THREAD

**Issue by ed0c** [tegan-lamoureux/Rotate-Spectre#5]
Hi !

I own a HP Spectre x360 13" convertible computer.

Here is my xinput --list :

`⎡ Virtual core pointer id=2[master pointer `
`⎜ ↳ Virtual core XTEST pointer id=4[slave pointer (2)]`
`⎜ ↳ ELAN0732:00 04F3:24DB id=10[slave pointer (2)]`
`⎜ ↳ SynPS/2 Synaptics TouchPad id=14[slave pointer (2)]`

So I'm changing the line of your script

`TOUCHSCREEN ="ELAN0732:00 04F3:2493"`

with

`TOUCHSCREEN ="ELAN0732:00 04F3:24DB"`

When I run the script, the screen display move on the right or left when I physically switch my computer to the right or left.
Unfortunately the touchscreen does not follow and remains in its initial configuration.

By digging a little and breaking down the script elements to turn the screen for example to the left :

`xrandr -o left`

then the touchscreen:

`xinput set-prop "ELAN0732:00 04F3:24DB" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1`

Well, it works.

So I think there's a problem in the script, but I can't put my finger on it.
Thank you for your help

**Comment by ed0c** [comment]
I fund a way to make it work : it seems that when you put a sleep(2) between the xrandr and the xinput command, it works....

**Comment by tegan-lamoureux** [comment]
Oh cool, glad you got it to work. I wonder if there's an issue with timing? 2 seconds seems like quite awhile, but at least it's working!
